-- ███████████████████████████████████████████████████████████████████████████ --                                                                                                                                  

Config = {}

Config.Framework = 1 -- (ESX == 1), (QB == 2)
Config.FrameworkExport = 'es_extended' -- (ESX == 'es_extended'), (QB == 'qb-core' - if QB comment the es_extended line in shared_scripts in fxmanifest.lua, add -- before the '@es_extended')

-- Ox_lib notification to everybody
Config.Ox_LibNotify = false
Config.ChatMessage = true

-- position?: 'top' or 'top-right' or 'top-left' or 'bottom' or 'bottom-right' or 'bottom-left' or 'center-right' or 'center-left'
Config.NotifyPosition = 'bottom-right'
Config.Icon = 'business-time'
Config.BusinessIcon = 'rectangle-ad'

-- amber alert (player must have phone to receive the messages)
-- LBPHONE INTEGRATION
Config.AmberAlert = true
Config.AmberAlertCommand = 'amberalert'
Config.AuthorizedJobs = { -- list of jobs that can use the command and required grade
    [1] = {job = 'police', grade = 0},
    --[2] = {job = 'ambulance', grade = 0},
}

---

-- I recommend to choose one of these.
Config.LbPhone = {
  Twitter = false,
  Instagram = false,
  YellowPages = true,
  Marketplace = false,
  Mail = false,
}

Config.AllowedJobs = {
  ["realestate"] = true,
  ["nbkpharmacy"] = true,
  ["nbkcustoms"] = true,
  ["hoodrichpawn"] = true,
  ["hookahlounge"] = true,
  ["topgear"] = true,
  ["lccustoms"] = true,
  ["ocs"] = true,
  ["thesaav"] = true,
  ["srtautos"] = true,
  ["topdeal"] = true,
  ["upnatom"] = true,
  ["outwest"] = true,
  ["munnapawnshop"] = true,
  ["ottosmechanic"] = true,
  ["puffpuffpass"] = true,
  ["autorepairs"] = true,
  ["casino"] = true,
  ["dreamworks"] = true,
  ["sacrunnapharmacy"] = true,
  ["crumblycookie"] = true,
  ["hayes"] = true,
  ["ctrrecords"] = true,
  ["tropicalheights"] = true,
  ["bahamas"] = true,
  ["vanillaunicorn"] = true,
  ["oasis"] = true,
  ["club77"] = true,
  ["paradise"] = true,
  ["hornys"] = true,
  ["aero"] = true,
  ["thotthotshairsalon"] = true,
  ["streetlabs"] = true,
  ["raqnwrench"] = true,
  ["harem"] = true,
  ["baddiesauto"] = true,
  ["mtkickz"] = true,
  ["bucksbucket"] = true,
  ["dzautorepairs"] = true,
  ["dzpawnshop"] = true,
  ["speedcustoms"] = true,
  ["dayday"] = true,
  ["stonegaterx"] = true,
  ["onestopshop"] = true,
  ["krazedrug"] = true,
  ["shroomacy"] = true,
  ["raqcity"] = true,
  ["jjfish"] = true,
  ["hoodrichpharm"] = true,

  -- Newly added (your list)
  ["smithsbodyworks"] = true,
  ["ebkpharmacy"] = true,
  ["escospharmacy"] = true,
  ["murdapawnshop"] = true,
  ["speedpawnshop"] = true,
  ["kushfactory"] = true,

  -- Old config jobs added now
  ["thevault"] = true,
  ["topclass"] = true,
  ["baddiestrap"] = true,
  ["baddieslashes"] = true,
  ["baddiesmechanic"] = true,
  ["speedpharmacist"] = true,

  -- Additional missing jobs from your list:
  ["police"] = true,
  ["ambulance"] = true,
  ["mechanic"] = true,
  ["fox4"] = true,
  ["pizzathis"] = true,
  ["pizzathat"] = true,
  ["nailsandsets"] = true,
  ["mpburgershot"] = true,
  ["georgiastatepolice"] = true,
  ["wvmechshop"] = true,
  ["supermarketsandy"] = true,
  ["cityhall"] = true,
  ["court"] = true,
  ["galaxy"] = true,
  ["coffeeshop"] = true,
  ["southwestgrill"] = true,
  ["rustybrowns"] = true,
  ["cupcakes"] = true,
  ["chinaland"] = true,
  ["jumpinjuice"] = true,
  ["ammoshop"] = true,
  ["apmechanic"] = true,
  ["apex"] = true,
  ["fettys"] = true,
  ["mafia"] = true,

  -- Added per request
  ["revline"] = true,
    ["dosebox"] = true,
  ["undergroundcustoms"] = true,
  ["malibuclub"] = true,
  ["baddiespawnshop"] = true,
  ["ricopharmacy"] = true,
  ["elmercado"] = true,
  ["catcafe"] = true,
  ["dkspharmacy"] = true,
  ["swaggpharmacy"] = true,
  ["bkbpharmacy"] = true,
  ["chinalandimports"] = true,
  ["trigdrug"] = true,
  ["elitemechanics"] = true
}

Config.RequiredGrade = {
  ["realestate"] = 0,
  ["nbkpharmacy"] = 0,
  ["nbkcustoms"] = 0,
  ["hoodrichpawn"] = 0,
  ["hookahlounge"] = 0,
  ["topgear"] = 0,
  ["autorepairs"] = 0,
  ["thesaav"] = 0,
  ["lccustoms"] = 0,
  ["ocs"] = 0,
  ["srtautos"] = 0,
  ["topdeal"] = 0,
  ["upnatom"] = 0,
  ["outwest"] = 0,
  ["casino"] = 0,
  ["munnapawnshop"] = 0,
  ["ottosmechanic"] = 0,
  ["puffpuffpass"] = 0,
  ["dreamworks"] = 0,
  ["sacrunnapharmacy"] = 0,
  ["crumblycookie"] = 0,
  ["hayes"] = 0,
  ["ctrrecords"] = 0,
  ["tropicalheights"] = 0,
  ["bahamas"] = 0,
  ["vanillaunicorn"] = 0,
  ["oasis"] = 0,
  ["club77"] = 0,
  ["paradise"] = 0,
  ["hornys"] = 0,
  ["aero"] = 0,
  ["thotthotshairsalon"] = 0,
  ["streetlabs"] = 0,
  ["raqnwrench"] = 0,
  ["harem"] = 0,
  ["baddiesauto"] = 0,
  ["mtkickz"] = 0,
  ["bucksbucket"] = 0,
  ["dzautorepairs"] = 0,
  ["dzpawnshop"] = 0,
  ["speedcustoms"] = 0,
  ["dayday"] = 0,
  ["stonegaterx"] = 0,
  ["onestopshop"] = 0,
  ["krazedrug"] = 0,
  ["shroomacy"] = 0,
  ["raqcity"] = 0,
    ["dosebox"] = 0,
  ["undergroundcustoms"] = 0,
  ["malibuclub"] = 0,
  ["baddiespawnshop"] = 0,
  ["ricopharmacy"] = 0,
  ["elmercado"] = 0,
  ["catcafe"] = 0,
  ["dkspharmacy"] = 0,
  ["swaggpharmacy"] = 0,
  ["bkbpharmacy"] = 0,
  ["chinalandimports"] = 0,
  ["trigdrug"] = 0,
  ["jjfish"] = 0,
  ["hoodrichpharm"] = 0,

  -- Newly added
  ["smithsbodyworks"] = 0,
  ["ebkpharmacy"] = 0,
  ["escospharmacy"] = 0,
  ["murdapawnshop"] = 0,
  ["speedpawnshop"] = 0,
  ["kushfactory"] = 0,

  -- Missing jobs added now
  ["thevault"] = 0,
  ["topclass"] = 0,
  ["baddiestrap"] = 0,
  ["baddieslashes"] = 0,
  ["baddiesmechanic"] = 0,
  ["speedpharmacist"] = 0,

  -- Added per request
  ["revline"] = 0,
  ["elitemechanics"] = 0,

  -- Extra jobs from your job list not in the config before
  ["police"] = 0,
  ["ambulance"] = 0,
  ["mechanic"] = 0,
  ["fox4"] = 0,
  ["pizzathis"] = 0,
  ["pizzathat"] = 0,
  ["nailsandsets"] = 0,
  ["mpburgershot"] = 0,
  ["georgiastatepolice"] = 0,
  ["wvmechshop"] = 0,
  ["supermarketsandy"] = 0,
  ["cityhall"] = 0,
  ["court"] = 0,
  ["galaxy"] = 0,
  ["coffeeshop"] = 0,
  ["southwestgrill"] = 0,
  ["rustybrowns"] = 0,
  ["cupcakes"] = 0,
  ["chinaland"] = 0,
  ["jumpinjuice"] = 0,
  ["ammoshop"] = 0,
  ["apmechanic"] = 0,
  ["apex"] = 0,
  ["fettys"] = 0,
  ["mafia"] = 0
}

Config.PromotionCosts = {
  ["realestate"] = 100,
  ["nbkpharmacy"] = 150,
  ["nbkcustoms"] = 150,
  ["hoodrichpawn"] = 150,
  ["hookahlounge"] = 150,
  ["autorepairs"] = 150,
  ["topgear"] = 150,
  ["lccustoms"] = 150,
  ["ocs"] = 150,
  ["munnapawnshop"] = 150,
  ["topdeal"] = 150,
  ["thesaav"] = 150,
  ["upnatom"] = 150,
  ["casino"] = 150,
  ["outwest"] = 150,
  ["ottosmechanic"] = 150,
  ["puffpuffpass"] = 150,
  ["dreamworks"] = 150,
  ["sacrunnapharmacy"] = 150,
  ["crumblycookie"] = 150,
  ["hayes"] = 150,
  ["ctrrecords"] = 150,
  ["tropicalheights"] = 150,
  ["bahamas"] = 150,
  ["vanillaunicorn"] = 150,
  ["oasis"] = 150,
  ["club77"] = 150,
  ["paradise"] = 150,
  ["hornys"] = 150,
  ["aero"] = 150,
  ["thotthotshairsalon"] = 150,
  ["streetlabs"] = 150,
  ["raqnwrench"] = 150,
  ["harem"] = 150,
  ["baddiesauto"] = 150,
  ["mtkickz"] = 150,
  ["bucksbucket"] = 150,
  ["dzautorepairs"] = 150,
  ["dzpawnshop"] = 150,
  ["speedcustoms"] = 150,
  ["dayday"] = 150,
  ["stonegaterx"] = 150,
  ["onestopshop"] = 150,
  ["krazedrug"] = 150,
  ["shroomacy"] = 150,
  ["raqcity"] = 150,
  ["jjfish"] = 150,
  ["hoodrichpharm"] = 150,

  -- Newly added
  ["smithsbodyworks"] = 150,
  ["ebkpharmacy"] = 150,
  ["escospharmacy"] = 150,
  ["murdapawnshop"] = 150,
  ["speedpawnshop"] = 150,
  ["kushfactory"] = 150,

  -- Missing jobs added now
  ["thevault"] = 150,
  ["topclass"] = 150,
  ["baddiestrap"] = 150,
  ["baddieslashes"] = 150,
  ["baddiesmechanic"] = 150,
  ["speedpharmacist"] = 150,

  -- Added per request
  ["revline"] = 150,
  ["elitemechanics"] = 150,

  -- Extra jobs from your job list not in the config originally
  ["police"] = 150,
  ["ambulance"] = 150,
  ["mechanic"] = 150,
  ["fox4"] = 150,
  ["pizzathis"] = 150,
  ["pizzathat"] = 150,
  ["nailsandsets"] = 150,
  ["mpburgershot"] = 150,
  ["georgiastatepolice"] = 150,
  ["wvmechshop"] = 150,
  ["supermarketsandy"] = 150,
  ["cityhall"] = 150,
  ["court"] = 150,
  ["galaxy"] = 150,
  ["coffeeshop"] = 150,
  ["southwestgrill"] = 150,
  ["rustybrowns"] = 150,
  ["cupcakes"] = 150,
  ["chinaland"] = 150,
  ["jumpinjuice"] = 150,
  ["ammoshop"] = 150,
  ["apmechanic"] = 150,
  ["apex"] = 150,
  ["fettys"] = 150,
    ["dosebox"] = 150,
  ["undergroundcustoms"] = 150,
  ["malibuclub"] = 150,
  ["baddiespawnshop"] = 150,
  ["ricopharmacy"] = 150,
  ["elmercado"] = 150,
  ["catcafe"] = 150,
  ["dkspharmacy"] = 150,
  ["swaggpharmacy"] = 150,
  ["bkbpharmacy"] = 150,
  ["chinalandimports"] = 150,
  ["trigdrug"] = 150,
  ["mafia"] = 150
}


Config.BlacklistWords = {
  "nigger",
  "niggr",
  "n1gger",
  "n1gg3r",
  "ngger",
  "n1ger",
  "n1g3r",
  "nigg3r",
  "ng3r",
  "nger",
  "faggot",
  "f@gg0t",
  "fag",
  "f@g",
  "fag0t",
  "fagot",
  "fagg0t",
  -- Add more blacklist words here
}

Config.CooldownTime = 120  -- Cooldown time in seconds

Config.Strings = {
  amber_alert = 'Amber Alert',
  you_are_not_allowed_amberalert = 'You are not allowed to use amber-alert.',
  business_promotion = 'Business Promotion',
  -- This one is for server-side that will show job name next to it.
  business_promotion2 = 'Business Promotion - ',
  job = 'Job: ',
  wait_for_promotion = 'Please wait before promoting your business again.',
  blacklisted_words = 'Your message contains a blacklisted-word.',
  not_enough_money = 'You do not have enough money to promote your business.',
  not_required_job_grade = 'You do not have the required job grade to promote your business.',
  you_are_not_allowed = 'You are not allowed to promote your business.',
  not_enough_cash = 'You do not have enough cash.',
  player_not_found = 'Player not found.'
}

-- ███████████████████████████████████████████████████████████████████████████ --
